### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by 7beggars** [matteograsso/visualize_pyphi#5]
What should be happening?

![image](https://user-images.githubusercontent.com/76716532/152690443-0b18b74c-903f-493d-aece-f07a2aa61187.png)

Full here https://github.com/7beggars/things/blob/main/IIT-4-vis-pyphi.ipynb

**Comment by matteograsso** [comment]
You should import FlatCauseEffectStructure as sep, not CauseEffectStructure.

In your import cell you should substitute line 6:
`from pyphi.models.subsystem import CauseEffectStructure as sep`
with:
`from pyphi.models.subsystem import FlatCauseEffectStructure as sep`
