### ISSUE TITLE
AttributeError: 'MaximallyIrreducibleCause' object has no attribute 'node_label

### ISSUE THREAD

**Issue by 7beggars** [matteograsso/visualize_pyphi#6]
thanks @matteograsso, , I can not generate the figure:

![image](https://user-images.githubusercontent.com/76716532/153102840-a3f33e00-7c9f-4426-8bcb-3479d5024fc5.png)

Also here full [ffle](https://github.com/7beggars/things/blob/main/IIT-4-vis-pyphi%20(copy%202).ipynb)

**Comment by matteograsso** [comment]
Can you check that you are using the latest version of visualize_pyphi?  Line 97 of visualize_ces.py should be:
`mice.mechanism, node_labels=mice.ria.node_labels, bold=bold, state=state`
and not:
`mice.mechanism, node_labels=mice.node_labels, bold=bold, state=state`

**Comment by 7beggars** [comment]
First I checked the version See below:

![image](https://user-images.githubusercontent.com/76716532/153294033-e53f8e7e-533a-4b20-9293-67b29cd4d572.png)

I forced the update using `pip install "git+https://github.com/matteograsso/visualize_pyphi.git"` this did not update `visualize_ces.py`, I also tried `pip install visualize-pyphi --upgrade` and  this did not update `visualize_ces.py`,  

Finally I downloaded the package directly and extracts on my site-packages, now `visualize-pyphi` is updated for respective` line 97 `but now I have the same error with updated file:

![image](https://user-images.githubusercontent.com/76716532/153296385-aa8f1df5-139d-40bc-b8ae-924bd2122d16.png)

NOTE 01: 

I noticed updates in the last hours on the [visualize-pyphi](https://github.com/matteograsso/visualize_pyphi/) and I tried again, at first the error persists, but a new mistake arose when I changed my ipynb source to a folder one level above:

![image](https://user-images.githubusercontent.com/76716532/153313524-827d5f10-3c1b-484e-9f8d-008785a3d1be.png)

NOTE 02:

Also when trying to run:

[Filling_the_slots.ipynb](https://github.com/matteograsso/visualize_pyphi/blob/main/Filling_the_slots.ipynb)

![image](https://user-images.githubusercontent.com/76716532/153318123-029aee9e-a406-4367-9768-e8faba404023.png)

**Comment by 7beggars** [comment]
During the last days there were improvements in the package, but what definitely decided for me was to directly download the [pyphi IIT 4.0](https://github.com/wmayner/pyphi/tree/feature/iit-4.0/pyphi)  (thanks @matteograsso) and `visualize-pyphi` for my `~ /site-packages/..`. In addition I manually executed `pip install -r * requirements.txt` from [pyphi](https://github.com/wmayner/pyphi/tree/feature/iit-4.0/) package. Then when trying to run the first cell of [example_notebook_iit_4.ipynb](https://github.com/matteograsso/visualize_pyphi/blob/main/Example_notebook_IIT_4.ipynb) I obtained the following message:

![image](https://user-images.githubusercontent.com/76716532/154201723-a6199b7f-e7bf-4449-bb61-8ccc99f68569.png)

and except that `pyphi_config.yml` parameters need to be changed manually:

![image](https://user-images.githubusercontent.com/76716532/154201990-e96d954e-499e-4a87-a91e-69dc2b116123.png)

For the case of this problem all the rest work:

https://user-images.githubusercontent.com/76716532/154200314-682aaf53-5bc1-4fa5-bfc4-5a16b4d462e2.mp4


https://user-images.githubusercontent.com/76716532/154200315-d9d1d876-f1c3-45b8-b5ce-c6f506411070.mp4


https://user-images.githubusercontent.com/76716532/154200325-ea0285f1-5bb1-4992-9480-ffe82c793a27.mp4


https://user-images.githubusercontent.com/76716532/154200334-88bba62c-fc83-44be-81f5-624768fac533.mp4


https://user-images.githubusercontent.com/76716532/154200348-764c60fa-b613-4aa6-bbf6-af2639d79688.mp4


https://user-images.githubusercontent.com/76716532/154200358-446b0bd4-bfd6-403d-9f17-224f4f7534b2.mp4

Note: Just weighing that `pip install pyphi` does not cause adequate installation, and it is necessary to do all installation manually.
